version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file ihug_pilot_v1.json --s3-bucket awspoclambda
                                   --output-template-file ihug_pilot_v1_template.json
artifacts:
  type: zip
  files:
    - ihug_pilot_v1_template.json